### PR TITLE
Add unload/load and reorganize extrude panel

### LINKED ISSUE #89: [Enhancement] Filament Change procedure
Heya... sry for posting that much first :/
But hope my ideas make your piece of software even better and better. Btw where is your donation link :D

So we all know how to get the filament change done inside a gcode on klipper but it is much more complicated (maybe just to me because I don't know how to do it right?) than it was on marlin.

So what I would like to see:

Icon for filament change. if we hit the button a new window pops up where we can enter the filamenttemperature needed for the change and a button to start the procedure.
For now I have a macro that always heats up to 225°C and that can be bit too low for ABS f.e.
If I throw this part of the macro out I have to first go manually to different menu heat up the nozzle to the wished temperature and wait until this is reached and then start my gcode macro to change the filament.

So this would be a quality of life change to make things a lot easier for dayli use.

### PR DESCRIPTION
**Pull request by alfrix**
- [x] Use load_filament and unload_filament macros and hide the buttons if not present

Fix #89
This PR (a 4th extruder will replace the temp shortcut)
2021-09-03-141216_480x320_scrot

master
2021-08-31-135654_480x320_scrot

this should help with #245

### CODE REVIEW

**Comment by jordanruthe** [comment]
I haven't done it yet, but I would like for Load/Unload to appear on this panel as well. Perhaps now is the time to address that

**Comment by alfrix** [comment]
And now with extruder colors!
2021-08-31-145118_480x320_scrot

**Comment by alfrix** [comment]
> I haven't done it yet, but I would like for Load/Unload to appear on this panel as well. Perhaps now is the time to address that

i haven't thought of that because  i use macros for that, perhaps 5 columns?

**Comment by alfrix** [comment]
This is the best organized i can think of right now, sacrificed the temperature shorcut
2021-08-31-151820_480x320_scrot

**Comment by alfrix** [comment]
One of the reasons for the reorganize is that in the current master german is broken:
2021-09-02-153837_480x320_scrot

**Comment by alfrix** [comment]
Solved
2021-09-02-173615_480x320_scrot

2021-09-02-173118_480x320_scrot

Purging just 1mm is usually pointless even for testing,  to fully purge is not uncommon to have to [waste 50 to 150 mm3](https://help.prusa3d.com/en/article/purging-volumes_125097)

Speed (mm/s) | Volume(mm3/s) | Usage
------------ | ------------ | -------------
1  | 2.4 | Purge TPU on bowden
2 | 4.8 | Purge Nylon or PLA at a slow rate
5 | 12 | Purge at fast rate
25 | 60 | Purge with a high volume hotend or Retracting

**Pull request merged**
