### PR TITLE
Update french translation

### PR DESCRIPTION
**Pull request by orobardet**
Update french translation with new string from #384.  
Plus it fix some of the existing translations.

This branch is based on #384.

### CODE REVIEW

**Comment by alfrix** [comment]
Why do i even bother

**Comment by orobardet** [comment]
> Why do i even bother
Hi !  
About what? Did I made something wrong?

**Comment by alfrix** [comment]
i left a review and even a screenshot...
147579539-f1cc78cc-3563-4337-befa-478d465a3c32
2 different translations for the same word and adding stuff that wasn't there

and it doesn't even fit, i will try to word wrap the dialog, but you cannot put any length of text everywhere this is an ui not a document, there are limited spaces

Adding "le" wasn't a great choice either, did the original string had "the" in it?
2022-01-03-112903_480x320_scrot

i will not be reviewing translations anymore, it is a waste of time if nobody reads them

**Comment by orobardet** [comment]
Well, I saw no review. I may have missed it, where is it?

> 2 different translations for the same word and adding stuff that wasn't there
For the different words between `Récupération "--hard"` and `Récupérer "--soft"`, it an error of mine, I saw it this morning (UTC+1) and I intent to fix it, but I'm at work currently and cannot _right now_.
I know the "--hard" and "--soft" are no perfect, but "Récupérer" is an invalid word in this context.

Would `Récupération hard` and `Récupération soft` be better?

> and it doesn't even fit, i will try to word wrap the dialog, but you cannot put any length of text everywhere this is an ui not a document, there are limited spaces

I knew about limitation. I checked and it fit when I test it on my setup. I will check again. 

> Adding "le" wasn't a great choice either, did the original string had "the" in it?
In english "the" is not necessary here. But in french "le" is. It's not valid without it.

I'm using KlipperScreen and I like it. 
I saw you made a lot of nice contribution to KlipperScreen the past monthes, I'm thankfull for you and Jordan for that, I just wanted to contribute too, at my level.
I pushed these PRs to help improve KlipperScreen. It also was to train myself on simple changes, before proposing more changes later (I'm working on a "voron" theme, and a way to filter out some temperature sensor in panel display).  

I do not intend to upset anyone, sorry if this is the case.  
But it's not a big deal, I'll fix it :). It does not break anything, it just makes some texts bit ugly (I did not test all themes).

**Comment by alfrix** [comment]
for the record, i'm not angry just sad because i tried to help and was ignored; I appreciate your contribution and hope that you don't get discouraged.
I've made the dialogs wrap long words, so you can put any length in those buttons, although it may not look very good on small screens but at least it wont break the ui

**Pull request merged**
