### PR TITLE
base_panel: added light toggle button where back button is used to be…

### PR DESCRIPTION
**Pull request by Flo-Kra**
… whenever no back button is displayed (only if a power device starting "light" in it´s name is configured. 
Does not affect original back-button behaviour. 

KlipperScreen_LightToggleButton
)

### CODE REVIEW

**Comment by AntoszHUN** [comment]
Now is it possible to adjust the brightness then?

**Comment by Flo-Kra** [comment]
> Now is it possible to adjust the brightness then?

No, as this button is only a shortcut so that the light can be toggled with one click instead of 3 or 4, regardless if currently printing or not. It uses the same backend functions as the light switch already available in the power menu. 
As it relies on functions of Moonraker (power device with name "light" configured in moonraker.conf) it can only do what´s supported there.

**Comment by AntoszHUN** [comment]
> 

I understand. Thanks for the reply!

**Comment by alfrix** [comment]
i simply do not agree with replacing navigation buttons with other actions.

**Pull request closed without merging**
