### PR TITLE
Installer: improvements

### LINKED ISSUE #317: Install script outputs black font on dark-themed console
Here is what the install script looks like on a dark themed gnome terminal:
image
The Font seems to be intentionally black, regardless of the set foreground or background color. Only after changing the background color the font gets visible:
image

The install script should either check what the background color is and use an appropriate foreground color, or it should set both foreground and background color such that both match, or (best of all) not set any color explicitly and use the default colorscheme of the terminal.

### LINKED ISSUE #334: Building wheel for vext.gi (setup.py) ... error
Hi. 
I'm getting the following error during installation process. After it's finished Klipper Screen is not working.

```
Building wheels for collected packages: vext.gi
  Building wheel for vext.gi (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/pi/.KlipperScreen-env/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1qtmugxa/vext-gi_0105c40b605f4165961fd8d42b7e2225/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1qtmugxa/vext-gi_0105c40b605f4165961fd8d42b7e2225/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qag5hwd2
       cwd: /tmp/pip-install-1qtmugxa/vext-gi_0105c40b605f4165961fd8d42b7e2225/
  Complete output (31 lines):
  running bdist_wheel
  running build
  /home/pi/.KlipperScreen-env/lib/python3.7/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    setuptools.SetuptoolsDeprecationWarning,
  installing to build/bdist.linux-armv6l/wheel
  running install
  vext.gi Install
  running install_data
  creating build
  creating build/bdist.linux-armv6l
  creating build/bdist.linux-armv6l/wheel
  creating build/bdist.linux-armv6l/wheel/vext.gi-0.7.4.data
  creating build/bdist.linux-armv6l/wheel/vext.gi-0.7.4.data/data
  creating build/bdist.linux-armv6l/wheel/vext.gi-0.7.4.data/data/share
  creating build/bdist.linux-armv6l/wheel/vext.gi-0.7.4.data/data/share/vext
  creating build/bdist.linux-armv6l/wheel/vext.gi-0.7.4.data/data/share/vext/specs
  copying gi.vext -> build/bdist.linux-armv6l/wheel/vext.gi-0.7.4.data/data/share/vext/specs
  running install_egg_info
  running egg_info
  writing vext.gi.egg-info/PKG-INFO
  writing dependency_links to vext.gi.egg-info/dependency_links.txt
  writing requirements to vext.gi.egg-info/requires.txt
  writing top-level names to vext.gi.egg-info/top_level.txt
  reading manifest file 'vext.gi.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.txt'
  writing manifest file 'vext.gi.egg-info/SOURCES.txt'
  Copying vext.gi.egg-info to build/bdist.linux-armv6l/wheel/vext.gi-0.7.4-py3.7.egg-info
  running install_scripts
  Install vext files:
  error: [Errno 2] No such file or directory: 'vext': 'vext'
  ----------------------------------------
  ERROR: Failed building wheel for vext.gi
  Running setup.py clean for vext.gi
Failed to build vext.gi
```

### PR DESCRIPTION
**Pull request by alfrix**
The problem occurs because vext and vext.gi are installed at the same time
we need to install the requirements in order

fixes #334 and #302 with d1905ca
fixes #317 with 7dc136d

### CODE REVIEW

**Comment by srbjessen** [comment]
Will this fix my issue as well?  Thanks for your amazing work, i love Klipperscreen 
https://github.com/jordanruthe/KlipperScreen/issues/334#issuecomment-974603456

**Comment by alfrix** [comment]
Yes fixes #334

**Comment by jordanruthe** [comment]
At this point I don't want to remove coloring, an option would be to make the dark grey not as dark.

**Comment by srbjessen** [comment]
Install went smoothly this time. Thank you for your hard work 🥇

**Comment by alfrix** [comment]
:smile: Thank you for the feedback

**Pull request merged**
