### PR TITLE
Fix german translation

### PR DESCRIPTION
**Pull request by hawkeyexp**

### CODE REVIEW

**Comment by jordanruthe** [comment]
Can you run the `update_translation_files.sh` and include that in this PR so the binary file is updated?

**Comment by hawkeyexp** [comment]
Hm, seems with latest commits the german translation has not been fixed - klipperscreen is still showing "Last" instrad of "Laden" - possible a leftover hardcoded part in the gui  (Filament change) ?!

**Comment by Elektrickser** [comment]
Hi Hawkeyexp,

I searched the msgid, but don't fount it in the code. In which panel you have this?

**Comment by hawkeyexp** [comment]
It's in the extrude panel if load and unload macro are available and the additional buttons are shown

**Comment by Elektrickser** [comment]
Wait a moment, i will make the current changes.
I see it.

**Pull request merged**
