### PR TITLE
Fix network panel showing blank

### LINKED ISSUE #312: Network is not displayed
Hello, thanks for KlipperScreen I really love it.

I have it running on two different printes. One show networks just fine while the other does not display anything but

Interface wlan0

The log file has the following lines:

```
2021-10-21 22:05:43,408 [screen.py:show_panel()] - Current panel hierarchy: ['main_panel', 'main_panel_config']
2021-10-21 22:05:45,860 [screen.py:_load_panel()] - Loading panel: network
2021-10-21 22:05:45,860 [screen.py:_load_panel()] - Panel path: /home/pi/KlipperScreen/panels/network.py
2021-10-21 22:05:45,938 [screen.py:show_panel()] - Attaching panel main_panel_config_network
2021-10-21 22:05:45,949 [screen.py:show_panel()] - Showing back. count: 2
2021-10-21 22:05:45,957 [screen.py:show_panel()] - Current panel hierarchy: ['main_panel', 'main_panel_config', 'main_panel_config_network']
2021-10-21 22:05:46,009 [functions.py:logging_exception_handler()] - Uncaught exception <class 'ValueError'>: 'OnAir' is not in list
Traceback:   File "/home/pi/KlipperScreen/panels/network.py", line 95, in load_networks
    self.add_network(conn_ssid, False)

  File "/home/pi/KlipperScreen/panels/network.py", line 187, in add_network
    pos = nets.index(ssid)
NoneType: None
2021-10-21 22:05:48,507 [screen.py:_menu_go_back()] - #### Menu go back
```

Can anyone give me a hint what is wrong?

Thanks
Jan

### PR DESCRIPTION
**Pull request by alfrix**
fixes  #312

### CODE REVIEW

**Comment by moelski** [comment]
Hi !
Will this fix wired connections as well? 
My connection screen looks like this: 
MobaXterm_IEhcm1j6EY

Dominik

**Comment by alfrix** [comment]
Maybe, post the your current log
or just modify the file, try and report back

**Comment by alfrix** [comment]
i found multiple issues, that need to be addressed:
The connected network doesn't remove the icon when disconnected (disconnect is working)
After connect KS is completely blank, probably a failed dialog.

i will close this until i have a more complete solution

**Comment by moelski** [comment]
> Maybe, post the your current log or just modify the file, try and report back

Which log file did you mean? 
The wired network is still not listed in den network panel - only the string eth0. 
If I can help in any way please let me know.

**Pull request closed without merging**
