### PR TITLE
Wifi manager

### PR DESCRIPTION
**Pull request by jordanruthe**
This addresses #141 . Opening a pull request for review and if there are any comments. This will be merged into the baseline in a couple of days if there are no issues.

Please note, there are logging statements in this branch that will output information (mainly WiFi connection information) that you may not want in log files. These logging statements will be removed before this is merged.

### CODE REVIEW

**Comment by jordanruthe** [comment]
wifi_manager

**Comment by nicedevil007** [comment]
Will it be possible to type in the password on connecting to an unknown wifi?
Maybe I missed it, but didn't saw any keyboard that was/is working with touch on KlipperScreen.

**Comment by jordanruthe** [comment]
@nicedevil007 
image

The keyboard should currently be working to add a bed mesh profile (if you have bed meshes)

**Comment by denziko76** [comment]
Greetings! I have updated, but unfortunately there is no manager on the network.

**Comment by jordanruthe** [comment]
@denziko76 Please make a GitHub issue and include the KlipperScreen.log file

**Pull request merged**
