### PR TITLE
Polish translation

### PR DESCRIPTION
**Pull request by apolkosnik**
PR contains Polish translation

### CODE REVIEW

**Comment by alfrix** [comment]
Some labels are too long, try to respect the original string lengths, be reasonable
a

**Comment by apolkosnik** [comment]
I'll take a look, thanks for the feedback

**Comment by apolkosnik** [comment]
Ok, I'm testing the updated translation. I've noticed that "hour" and "hours" are not in the .pot file.

**Comment by apolkosnik** [comment]
I've played with Poedit a little, and it looks like "hour" can have more than two forms in some languages, I've also updated the KlipperScreen.pot file. Other language translations might need to be updated to have "hour" translated in the dropdown for the "Screen Power Off Time"

**Comment by alfrix** [comment]
The pot file its autogenerated, the script will erase your changes when it runs, plurals need to be added in the py files with `ngettext` or something like that, and the script needs to be updated to accept plurals `keyword=_:1,2`...

The translation looks ok in the ui now, there is a minor issue with the system panel that i will fix

**Pull request merged**
