### PR TITLE
some other fixes for ITA Lang

### PR DESCRIPTION
**Pull request by pappicio**
fixed and updated .po file, and updated .mo file for italian languge (if .mo is not the last, compiled with same .mo file, new fixes are hidden.)

### CODE REVIEW

**Review by alfrix — CHANGES_REQUESTED** [review]
The 5 strings that have "#~" are not part of master, this means that you are using an outdated PO file

**Comment by pappicio** [comment]
so, I have to use new pot file and recompile all parts?

**Comment by alfrix** [comment]
always use the most recent version when doing a pr

**Comment by pappicio** [comment]
ok, I'll provide to delete outdated strings, thanks.

**Pull request closed without merging**
